site_name: arcanex-sdk-js

theme: readthedocs

markdown_extensions:
  - admonition

nav:
  - Overview: index.md
  - API:
      - Account: api/account.md
      - TrxBuilder: api/trxbuilder.md
      - Event: api/subscriber.md
      - ACNet: api/acnrpc.md

  - internals:
      - Account: internals/account.md
      - Transaction: internals/transactions.md
      - JSONRPC: internals/rpc.md
  - examples:
      - Explorer:
          - Requirements: examples/explorer/srs.md
      - Wallet:
          - Requirements: examples/wallet/srs.md
