site_name: arcanex-sdk-js

theme: readthedocs

markdown_extensions:
  - admonition

nav:
  - Overview: index.md
  - ACNet: acnet.md
  - Event Subscription: subscriber.md
  - RPC: rpc.md
  - examples:
      - Explorer:
          - SRS: examples/explorer/srs.md
      - Wallet:
          - SRS: examples/wallet/srs.md
  - internals:
      - Account: internals/account.md
      - Transaction: internals/transactions.md
