site_name: rigo-sdk-js

theme: readthedocs

markdown_extensions:
  - admonition

nav:
  - Overview:
    - Key Features: index.md
    - Quick Start: quick.md
  - API:
    - Javascript API:
      - Account: api/account.md
      - TrxBuilder: api/trxbuilder.md
      - Subscriber: api/subscriber.md
      - RWeb3: api/rweb3.md
    - RPC API: api/rpc.md
  - internals:
      - Account: internals/account.md
      - Transaction: internals/transactions.md
  - examples:
      - Explorer:
          - Requirements: examples/explorer/srs.md
      - Wallet:
          - Requirements: examples/wallet/srs.md
